# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "sudo apt-get update -y"
    - "sudo debconf-set-selections preseed.txt"
    - "sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -q -y postfix syslog-ng sasl2-bin libsasl2-2 libsasl2-modules net-tools"
    - "composer update"
    - "sudo sed -i 's/#SYSLOGNG_OPTS=\"--no-caps\"/SYSLOGNG_OPTS=\"--no-caps\"/' /etc/default/syslog-ng"
    - "sudo cp /opt/etc/default/saslauthd /etc/default/"
    - "sudo touch /etc/sasldb2 && sudo chown postfix:sasl /etc/sasldb2"

  run:
    - "sudo php -f /opt/bin/smtp-update-config.php"
    - "sudo service syslog-ng restart"
    - "sudo service postfix start"

  log:
    - "tail -f /var/log/mail.log"

  test:
    - "vendor/bin/tester test/"
    #- "php -f bin/test-sasl-auth.php"

